😎 Migrates to uv package manager

diff --git a/.github/workflows/pytest-with-postgres.yml b/.github/workflows/pytest-with-postgres.yml
--- a/.github/workflows/pytest-with-postgres.yml
+++ b/.github/workflows/pytest-with-postgres.yml
@@ -13,11 +13,6 @@ on:
         type: string
         default: Codecov
 
-      pdm_args:
-        description: Install args for pdm
-        type: string
-        default: -G test
-
       pytest_args:
         description: Additional args to pass to pytest
         type: string
@@ -49,24 +44,23 @@ jobs:
           - 5432:5432
 
     steps:
-      - name: 📰 Checkout
-        uses: actions/checkout@v6
+    - name: 📰 Checkout
+      uses: actions/checkout@v6
+      with:
+        fetch-depth: 0
 
-      - name: 📦 Set up PDM
-        uses: pdm-project/setup-pdm@v4
-        with:
-          python-version: ${{ inputs.python_version }}
-          cache: true
+    - name: 😎 Install uv
+      uses: astral-sh/setup-uv@v7
+      with:
+        python-version: ${{ inputs.python_version }}
 
-      - name: 🚧 Install dependencies
-        run: pdm install ${{ inputs.pdm_args }}
+    
+    - name: 🧪 Run pytest suite
+      run: uv run pytest -v --cov --cov-report lcov ${{ inputs.pytest_args }}
 
-      - name: 🧪 Run pytest suite
-        run: pdm run pytest -v --cov --cov-report lcov ${{ inputs.pytest_args }}
-
-      - name: 📈 Uploade coverage report
-        # run this step, even if the tests fail
-        if: success() || failure()
-        uses: codecov/codecov-action@v5
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
+    - name: 📈 Uploade coverage report
+      # run this step, even if the tests fail
+      if: success() || failure()
+      uses: codecov/codecov-action@v5
+      with:
+        token: ${{ secrets.CODECOV_TOKEN }}
diff --git a/.github/workflows/pytest.yml b/.github/workflows/pytest.yml
--- a/.github/workflows/pytest.yml
+++ b/.github/workflows/pytest.yml
@@ -13,10 +13,10 @@ on:
         type: string
         default: Codecov
 
-      pdm_args:
-        description: Install args for pdm
+      pip_args:
+        description: Install args for pip
         type: string
-        default: -G test
+        default: .[test]
 
       pytest_args:
         description: Additional args to pass to pytest
@@ -29,24 +29,20 @@ jobs:
     environment: ${{ inputs.environment }}
 
     steps:
-      - name: 📰 Checkout
-        uses: actions/checkout@v6
+    - name: 📰 Checkout
+      uses: actions/checkout@v6
+      with:
+        fetch-depth: 0
 
-      - name: 📦 Set up PDM
-        uses: pdm-project/setup-pdm@v4
-        with:
-          python-version: ${{ inputs.python_version }}
-          cache: true
+    - name: 😎 Install uv
+      uses: astral-sh/setup-uv@v7
 
-      - name: 🚧 Install dependencies
-        run: pdm install ${{ inputs.pdm_args }}
+    - name: 🧪 Run pytest suite
+      run: pytest -v --cov --cov-report lcov ${{ inputs.pytest_args }}
 
-      - name: 🧪 Run pytest suite
-        run: pdm run pytest -v --cov --cov-report lcov ${{ inputs.pytest_args }}
-
-      - name: 📈 Uploade coverage report
-        # run this step, even if the tests fail
-        if: success() || failure()
-        uses: codecov/codecov-action@v5
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
+    - name: 📈 Uploade coverage report
+      # run this step, even if the tests fail
+      if: success() || failure()
+      uses: codecov/codecov-action@v5
+      with:
+        token: ${{ secrets.CODECOV_TOKEN }}
